spring.application.name=tasks

spring.datasource.url=jdbc:postgresql://localhost:5432/tasks
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

app.jwt.secret-base64=${JWT_SECRET_BASE64}
app.jwt.access-token-ttl=15m
