spring.application.name=tasks

spring.datasource.url=jdbc:postgresql://localhost:5432/tasks-test
spring.datasource.username=postgres
spring.datasource.password=wow4657

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true