CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE tasks
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    description      VARCHAR(255),
    status           VARCHAR(255) NOT NULL,
    assigned_user_id BIGINT,

    CONSTRAINT fk_tasks_assigned_user
        FOREIGN KEY (assigned_user_id)
            REFERENCES users (id),

    CONSTRAINT tasks_status_check
        CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE'))
);
